// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SUTUTWebApp.Models.Entities;

#nullable disable

namespace SUTUTWebApp.Migrations
{
    [DbContext(typeof(MasterContext))]
    partial class MasterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Atletskiklub", b =>
                {
                    b.Property<int>("AklubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AKlubId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AklubId"));

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Osnovano")
                        .HasColumnType("int");

                    b.HasKey("AklubId")
                        .HasName("PK__ATLETSKI__4E23C839BDF30C02");

                    b.ToTable("ATLETSKIKLUB", (string)null);
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Kategorija", b =>
                {
                    b.Property<int>("KategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorijaId"));

                    b.Property<double>("Duljina")
                        .HasColumnType("float");

                    b.Property<int>("MaxBrojTrkaca")
                        .HasColumnType("int")
                        .HasColumnName("Max_broj_trkaca");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<DateOnly>("Početak")
                        .HasColumnType("date");

                    b.Property<decimal>("Startnina")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TipId")
                        .HasColumnType("int");

                    b.Property<int>("UtrkaId")
                        .HasColumnType("int");

                    b.HasKey("KategorijaId")
                        .HasName("PK__KATEGORI__6C3B8FEEA9386602");

                    b.HasIndex("TipId");

                    b.HasIndex("UtrkaId");

                    b.ToTable("KATEGORIJA", (string)null);
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Organizator", b =>
                {
                    b.Property<int>("OrganizatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizatorId"));

                    b.Property<string>("BrojMobitela")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Broj_mobitela");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Oib")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("OIB");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("VrstaOrganizatoraId")
                        .HasColumnType("int");

                    b.Property<string>("WebStranica")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Web_stranica");

                    b.HasKey("OrganizatorId")
                        .HasName("PK__ORGANIZA__7464266AB917FA53");

                    b.HasIndex("VrstaOrganizatoraId");

                    b.ToTable("ORGANIZATOR", (string)null);
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Rezultat", b =>
                {
                    b.Property<int>("RezultatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RezultatId"));

                    b.Property<TimeOnly?>("FinalnoVrijeme")
                        .HasColumnType("time")
                        .HasColumnName("Finalno_vrijeme");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<int>("StatusRezultataId")
                        .HasColumnType("int");

                    b.Property<int>("TrkacId")
                        .HasColumnType("int");

                    b.HasKey("RezultatId")
                        .HasName("PK__REZULTAT__447B09FB9915679D");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("StatusRezultataId");

                    b.HasIndex(new[] { "TrkacId", "KategorijaId" }, "UQ_Trkac_Kategorija")
                        .IsUnique();

                    b.ToTable("REZULTAT", (string)null);
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Statusrezultatum", b =>
                {
                    b.Property<int>("StatusRezultataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusRezultataId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StatusRezultataId")
                        .HasName("PK__STATUSRE__E1B46CB0331E663B");

                    b.ToTable("STATUSREZULTATA", (string)null);
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Statusutrke", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StatusId")
                        .HasName("PK__STATUSUT__C8EE20632978266A");

                    b.ToTable("STATUSUTRKE", (string)null);
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Tipkategorije", b =>
                {
                    b.Property<int>("TipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TipId")
                        .HasName("PK__TIPKATEG__2DB1A1C81952CDB9");

                    b.ToTable("TIPKATEGORIJE", (string)null);
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Trening", b =>
                {
                    b.Property<int>("TreningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreningId"));

                    b.Property<double>("Duljina")
                        .HasColumnType("float");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<TimeOnly>("Trajanje")
                        .HasColumnType("time");

                    b.Property<int>("TrkacId")
                        .HasColumnType("int");

                    b.HasKey("TreningId")
                        .HasName("PK__TRENING__3B04A8D3444F6F93");

                    b.HasIndex("TrkacId");

                    b.ToTable("TRENING", (string)null);
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Trkac", b =>
                {
                    b.Property<int>("TrkacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrkacId"));

                    b.Property<int?>("AklubId")
                        .HasColumnType("int")
                        .HasColumnName("AKlubId");

                    b.Property<DateOnly?>("DatumRodenja")
                        .HasColumnType("date")
                        .HasColumnName("Datum_rodenja");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nacionalnost")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Spol")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("TrkacId")
                        .HasName("PK__TRKAC__1B133CCFD36A1F7E");

                    b.HasIndex("AklubId");

                    b.ToTable("TRKAC", (string)null);
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Utrka", b =>
                {
                    b.Property<int>("UtrkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtrkaId"));

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OrganizatorId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("UtrkaId")
                        .HasName("PK__UTRKA__038172C35314E55A");

                    b.HasIndex("OrganizatorId");

                    b.HasIndex("StatusId");

                    b.ToTable("UTRKA", (string)null);
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Vrstaorganizator", b =>
                {
                    b.Property<int>("VrstaOrganizatoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VrstaOrganizatoraId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("VrstaOrganizatoraId")
                        .HasName("PK__VRSTAORG__6B1325DB1F74A794");

                    b.ToTable("VRSTAORGANIZATOR", (string)null);
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Kategorija", b =>
                {
                    b.HasOne("SUTUTWebApp.Models.Entities.Tipkategorije", "Tip")
                        .WithMany("Kategorijas")
                        .HasForeignKey("TipId")
                        .IsRequired()
                        .HasConstraintName("FK__KATEGORIJ__TipId__4BCC3ABA");

                    b.HasOne("SUTUTWebApp.Models.Entities.Utrka", "Utrka")
                        .WithMany("Kategorijas")
                        .HasForeignKey("UtrkaId")
                        .IsRequired()
                        .HasConstraintName("FK__KATEGORIJ__Utrka__4AD81681");

                    b.Navigation("Tip");

                    b.Navigation("Utrka");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Organizator", b =>
                {
                    b.HasOne("SUTUTWebApp.Models.Entities.Vrstaorganizator", "VrstaOrganizatora")
                        .WithMany("Organizators")
                        .HasForeignKey("VrstaOrganizatoraId")
                        .IsRequired()
                        .HasConstraintName("FK__ORGANIZAT__Vrsta__3B95D2F1");

                    b.Navigation("VrstaOrganizatora");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Rezultat", b =>
                {
                    b.HasOne("SUTUTWebApp.Models.Entities.Kategorija", "Kategorija")
                        .WithMany("Rezultats")
                        .HasForeignKey("KategorijaId")
                        .IsRequired()
                        .HasConstraintName("FK__REZULTAT__Katego__536D5C82");

                    b.HasOne("SUTUTWebApp.Models.Entities.Statusrezultatum", "StatusRezultata")
                        .WithMany("Rezultats")
                        .HasForeignKey("StatusRezultataId")
                        .IsRequired()
                        .HasConstraintName("FK__REZULTAT__Status__51851410");

                    b.HasOne("SUTUTWebApp.Models.Entities.Trkac", "Trkac")
                        .WithMany("Rezultats")
                        .HasForeignKey("TrkacId")
                        .IsRequired()
                        .HasConstraintName("FK__REZULTAT__TrkacI__52793849");

                    b.Navigation("Kategorija");

                    b.Navigation("StatusRezultata");

                    b.Navigation("Trkac");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Trening", b =>
                {
                    b.HasOne("SUTUTWebApp.Models.Entities.Trkac", "Trkac")
                        .WithMany("Trenings")
                        .HasForeignKey("TrkacId")
                        .IsRequired()
                        .HasConstraintName("FK__TRENING__TrkacId__5649C92D");

                    b.Navigation("Trkac");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Trkac", b =>
                {
                    b.HasOne("SUTUTWebApp.Models.Entities.Atletskiklub", "Aklub")
                        .WithMany("Trkacs")
                        .HasForeignKey("AklubId")
                        .HasConstraintName("FK__TRKAC__AKlubId__46136164");

                    b.Navigation("Aklub");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Utrka", b =>
                {
                    b.HasOne("SUTUTWebApp.Models.Entities.Organizator", "Organizator")
                        .WithMany("Utrkas")
                        .HasForeignKey("OrganizatorId")
                        .IsRequired()
                        .HasConstraintName("FK__UTRKA__Organizat__405A880E");

                    b.HasOne("SUTUTWebApp.Models.Entities.Statusutrke", "Status")
                        .WithMany("Utrkas")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__UTRKA__StatusId__414EAC47");

                    b.Navigation("Organizator");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Atletskiklub", b =>
                {
                    b.Navigation("Trkacs");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Kategorija", b =>
                {
                    b.Navigation("Rezultats");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Organizator", b =>
                {
                    b.Navigation("Utrkas");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Statusrezultatum", b =>
                {
                    b.Navigation("Rezultats");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Statusutrke", b =>
                {
                    b.Navigation("Utrkas");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Tipkategorije", b =>
                {
                    b.Navigation("Kategorijas");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Trkac", b =>
                {
                    b.Navigation("Rezultats");

                    b.Navigation("Trenings");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Utrka", b =>
                {
                    b.Navigation("Kategorijas");
                });

            modelBuilder.Entity("SUTUTWebApp.Models.Entities.Vrstaorganizator", b =>
                {
                    b.Navigation("Organizators");
                });
#pragma warning restore 612, 618
        }
    }
}
